### ISSUE TITLE
Firebase deploy not working

### ISSUE THREAD

**Issue by daffl** [donejs/deploy#49]
And probably has not for a while, we just didn't notice it because the command still completes successfully, showing the following error though:

```
 Error
    at Error.FirebaseError (node_modules/firebase-tools/lib/error.js:11:17)
    at module.exports (node_modules/firebase-tools/lib/responseToError.js:26:10)
    at Request._callback (node_modules/firebase-tools/lib/api.js:32:23)
    at Request.self.callback (node_modules/firebase-tools/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (node_modules/firebase-tools/node_modules/request/request.js:1044:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (node_modules/firebase-tools/node_modules/request/request.js:965:12)
  name: 'FirebaseError',
  message: 'AuError: Command `node_modules/.bin/deploy` did not complete successfully
    at ChildProcess.<anonymous> (node_modules/donejs-cli/lib/utils.js:38:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
```

**Comment by matthewp** [comment]
Do you know if you are getting a new (looking) Firebase Console interface in the browser? I think it's related to that. We need to upgrade to the new version of firebase-tools to support the new console. Hopefully this is the same issue.

**Comment by daffl** [comment]
Yes, we just migrated. I moved to deploying directly with the new firebase-tools.

Honestly, seeing how much work it is to maintain donejs deploy, I'm wondering if we should deprecate it. It's really just a two line NPM script getting the Firebase deploy working  with `firebase-tools` (which DoneJS can still add) and for S3 you can just use one of the existing upload scripts.

**Comment by matthewp** [comment]
Ah, that's a good idea, so `donejs add firebase` (which @chasenlehara already created) could just set the npm deploy script to use that.  What about CI, does it work there too?
